version: '3.9'

services:
    app:
        container_name: desafio_gazin_app
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/var/www/html
        networks:
            - laravel

    api:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./backend:/var/www/html
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: postgres:13
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: desafio_gazin
            POSTGRES_USER: gazin
            POSTGRES_PASSWORD: 123456
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

networks:
    laravel:

volumes:
    pgdata:
